version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
      prefix: 'fix'
      include: 'scope'
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: npm
  directory: "/web/js/"
  schedule:
    interval: weekly
  commit-message:
    prefix: 'fix'
    include: 'scope'
  open-pull-requests-limit: 10
  versioning-strategy: increase
