creation_rules:
  - age:
      - age1c44428zkhhkqhtfh8r7qwf7y000hyvcsskue8nm22g3j5pqwmapq6pcpqy
    path_regex: "pkg/profiles/config-unittest.yml"
    encrypted_regex: ""

  - age:
      - age1rekch73u43q89fq4ajvq4utud2dp3jvvc4eefer42us4kgjal9vs2juvx7 # Gunstein Desktop
      - age1gvqc0qnsz7s4sfyffda6ctda4aah2drae0lvkug499hy6ckgxyvqsqcqh6 # Gunstein Laptop
      - age1s5m5e78an6dp9sxlyjqknzx2slazw604fdw2l6jzump5w6samv5qypc5hw # Cloud
    encrypted_regex: "(api_key|secret|password)"
    path_regex: "pkg/profiles/config.*yml"
