name: Build and Push Docker Image to Docker Hub

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Extract tag name
        id: vars
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o caesura main.go

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/caesura:${{ env.TAG_NAME }} .

      - name: Push Docker image
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/caesura:${{ env.TAG_NAME }}
